# -*- coding: utf-8 -*-
"""Project2Part2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111F9E6BX45TNL0_xNM9p0YTDgH_cUMDV
"""

import seaborn as sns
import pandas as pd

df = pd.read_csv("supermarket_sales.csv")

sns.countplot(data=df, x='Product line')

sns.countplot(data=df, x='Payment')

sns.boxplot(data=df, x='Branch', y='Total')

sns.histplot(data=df, x='Quantity', bins=20)

sns.histplot(data=df, x='Total', bins=20)

sns.barplot(data=df, x='Product line', y='Total')

sns.barplot(data=df, x='Gender', y='Total')

sns.violinplot(data=df, x='Product line', y='Total')

sns.violinplot(data=df, x='Payment', y='Total')

sns.scatterplot(data=df, x='Quantity', y='Total')

sns.lineplot(data=df, x='Date', y='Total')

sns.heatmap(df.corr(), cmap='coolwarm', annot=True)