# -*- coding: utf-8 -*-
"""movie_recommendation_system

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACrA7D78FxRubvNoJKSZLZUtIFTlOqvA
"""

import requests
from bs4 import BeautifulSoup
import json
import time

# Ask the user for their favorite movie
movie = input("Please enter your favorite movie: ")

# Use web scraping to get information about the user's favorite movie from IMDb
url = "https://www.imdb.com/find?q=" + movie + "&s=tt"
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, "html.parser")

# Get the movie ID
movie_id = soup.findAll('a', class_="ipc-metadata-list-summary-item__t")[0].get('href').split('/')[2]

# Print the movie ID
print("Movie ID:", movie_id)

# Use the TMDb API to get a list of similar movies
tmdb_api_key = "1db4e907f5fdb12f5e8f598eb3806282"  
tmdb_url = f"https://api.themoviedb.org/3/movie/{movie_id}/similar?api_key={tmdb_api_key}&language=en-US&page=1"


# Add a delay before making the API request
time.sleep(1)

tmdb_response = requests.get(tmdb_url)
tmdb_data = json.loads(tmdb_response.content)

# Extract the list of similar movies
similar_movies = tmdb_data.get("results", [])

# Print out the list of similar movies
print("Similar Movies:")
for movie in similar_movies:
    print(movie["title"])

